define:
  &log_level 'DEBUG'
version: 1
formatters:
  simple:
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: *log_level
    formatter: simple
    filters:
      - secrets_masking_filter
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: *log_level
    formatter: simple
    filters:
      - secrets_masking_filter
    filename: ${OUTPUT_DIR}/logs/aideas.log
    maxBytes: 409600
    backupCount: 9
loggers:
  app:
    level: *log_level
    handlers: [console, file]
    propagate: false
  content_publisher:
    level: *log_level
    handlers: [console, file]
    propagate: false
root:
  level: *log_level
  handlers: [console, file]
filters:
  secrets_masking_filter:
    (): app.io.logging.SecretsMaskingLogFilter
    patterns:
      - ""
